# -*- coding: utf-8 -*-
"""SAFEUrja

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dpHAGylD27c8OIXYaksYQOFGPj7gP4KK
"""

import streamlit as st
import numpy as np
import datetime

st.set_page_config(page_title="SAFE Urja", page_icon="☀️", layout="centered")
st.title("☀️ SAFE Urja — Smart Analytics For Efficient Urja")
st.subheader("AI-powered rooftop solar guidance for efficient energy use and storage")

with st.sidebar:
    st.header("User Input")
    daily_usage = st.number_input("Daily electricity usage (kWh)", 1.0, 100.0, 10.0)
    battery_capacity = st.number_input("Battery storage capacity (kWh)", 1.0, 50.0, 5.0)
    location = st.text_input("City/Location", "Delhi")

today = datetime.date.today()
rng = np.random.default_rng(today.toordinal())
predicted_generation = float(np.round(rng.uniform(5, 15), 2))

if predicted_generation >= daily_usage:
    storage_needed = daily_usage * 0.3
else:
    storage_needed = (daily_usage - predicted_generation) + (daily_usage * 0.3)

st.write(f"📍 Location: {location}")
st.write(f"☀️ Predicted Solar Generation Today: **{predicted_generation} kWh**")
st.write(f"⚡ Daily Usage: **{daily_usage} kWh**")
st.write(f"🔋 Battery Capacity: **{battery_capacity} kWh**")
st.write(f"💡 Recommended Extra Storage (stormy/cloudy): **{storage_needed:.2f} kWh**")

if battery_capacity < storage_needed:
    st.error("Your current battery capacity may be insufficient for backup needs.")
else:
    st.success("Your battery storage looks sufficient for today’s needs.")

st.markdown("---")
st.caption("Prototype: next steps include real weather/irradiance data, GIS rooftop mapping, and trained AI forecasting.")