# -*- coding: utf-8 -*-
"""SAFEUrja

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dpHAGylD27c8OIXYaksYQOFGPj7gP4KK
"""

# Title
st.title("☀️ SAFE Urja - Smart Analytics For Efficient Urja")
st.subheader("AI-powered rooftop solar guidance for efficient energy use and storage")

# User input
st.sidebar.header("User Input")
daily_usage = st.sidebar.number_input("Enter your daily electricity usage (kWh)", min_value=1.0, max_value=100.0, value=10.0)
battery_capacity = st.sidebar.number_input("Enter your battery storage capacity (kWh)", min_value=1.0, max_value=50.0, value=5.0)
location = st.sidebar.text_input("Enter your city/location", "Delhi")

# Mock AI solar generation prediction
today = datetime.date.today()
np.random.seed(today.day)
predicted_generation = round(np.random.uniform(5, 15), 2)  # in kWh

# Storage recommendation logic
if predicted_generation >= daily_usage:
    storage_needed = daily_usage * 0.3  # suggest 30% buffer
else:
    storage_needed = (daily_usage - predicted_generation) + (daily_usage * 0.3)

# Display results
st.write(f"📍 Location: {location}")
st.write(f"🔋 Battery Capacity: {battery_capacity} kWh")
st.write(f"☀️ Predicted Solar Generation Today: **{predicted_generation} kWh**")
st.write(f"⚡ Your Daily Usage: **{daily_usage} kWh**")
st.write(f"💡 Recommended Extra Storage for Stormy/Cloudy Days: **{round(storage_needed, 2)} kWh**")

# Alert for insufficient storage
if battery_capacity < storage_needed:
    st.error("⚠️ Your current battery capacity may be insufficient for backup needs.")
else:
    st.success("✅ Your battery storage is sufficient for today’s needs.")

# Future scope
st.markdown("---")
st.markdown("### 🚀 Future Add-ons")
st.markdown("- AI model trained on real solar irradiance + weather data")
st.markdown("- GIS mapping for rooftop solar potential")
st.markdown("- Cost-saving and CO2 reduction dashboard")